name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'LiangLouise'
        reponame: 'qpack_viewer'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        gitemail: 'royliang5@gmail.com'
        gitname: 'LiangLouise'
